### ISSUE TITLE
May 243 row has the error

### ISSUE THREAD

**Issue by rmalenko** [fayetted/nagios-check_iostat#1]
`PERFDATA=" | total_io_sec'=$tps; read_io_sec=$read_sec; write_io_sec=$written_sec; kbytes_read_sec=$kbytes_read_sec; kbytes_written_sec=$kbytes_written_sec;"`

Should be  **total_io_sec** instead  **total_io_sec'**?

**Comment by fayetted** [comment]
Fixed in code.  Thanks for reporting and providing the fix.
